### PR TITLE
Created an abstract class for feature evaluators

### PR DESCRIPTION
**Pull request by wahleric**
-Created FeatureEvaluator as an interface that all feature evaluators can implement
-Refactored existing feature evaluators to implement the interface (did not change underlying evaluation)

UPDATE:
-Changed the interface to an abstract class instead. The abstract class makes more sense as each evaluator function shares some identical functionality (i.e. returning its featureID from the getFeatureID() method), and also so that we can declare default functionality for the evaluateDocumentChanges or evaluateAnnotationModelChanges, rather than implementing the same default functionality in each subclass individually

### CODE REVIEW

**Review by johnbarUW — COMMENTED** [review]
I like having a interface for all evaluation features. There is one thing that may be worth discussing:

Should we break up the Evaluator lists into separate lists? One that needs to evaluate document changes and another that needs to evaluate AnnotationModel changes? There is a case to be made for keeping it simple like it is and just returning false on any changes we don't care about, however we could also design it to just never run an evaluation function on a change that that specific function doesn't care about.

We should consider this from an on-going perspective. There are probably going to be 1-3 other types of events we'll use in this project. Do we just continually add them to evaluators that don't need it? Or maybe some evaluators will use multiple types of change events - in that case having them in redundant lists seems like a poor choice as well.

I'm good with either design, but it's definitely worth talking about and deciding as a group on.

**Comment by wahleric** [comment]
I thought about that, but another thing to think about is that some evaluation functions might take both into account. For example, I almost have a working AddImportEvaluator that uses both document changes and annotation model changes (I can show you later how it works). I think in terms of code organization, it seems a bit simpler this way to have all evaluator functions in one list.

It is a little odd to have a function to always return false, but then again having that function in there also leaves the door open to using it later on if we find some way to incorporate it into a given evaluator function. In terms of performance, I think the impact of having this be the case is very negligible.

**Review by johnbarUW — APPROVED** [review]
Looks good. I like using an abstract class for this much more than an interface

**Review by DavidThien — APPROVED** [review]
Looks good!

**Pull request merged**
